"""
Builds a 3D web viewer using Three.js for the generated .ply meshes.
Looks for:
  - outputs/sfm_out/<Garment>/mesh.ply (preferred)
  - outputs/sfm_out/<Garment>/sparse_cloud.ply (fallback)
"""

import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SFM_OUT_DIR = os.path.join(ROOT, "outputs", "sfm_out")
VIEWER_DIR = os.path.join(ROOT, "viewer")
MODELS_DIR = os.path.join(VIEWER_DIR, "models")

os.makedirs(VIEWER_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>__TITLE__ - 3D Viewer</title>
    <style>
        :root { --gold: #c9a24a; --bg: #0e0d0b; }
        body {
            margin: 0; padding: 0; overflow: hidden;
            background: radial-gradient(ellipse at center, #1b1812 0%, #080706 100%);
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            color: #eee7d6;
        }
        #ui-layer {
            position: absolute; top: 20px; left: 0; width: 100%;
            text-align: center; pointer-events: none;
        }
        h1 {
            font-size: 1.2rem; font-weight: 600; letter-spacing: 0.08em;
            text-transform: uppercase; color: var(--gold); margin: 0 0 4px 0;
        }
        .sub { font-size: 0.8rem; color: #a89f89; }
        .hint {
            position: absolute; bottom: 30px; left: 50%; transform: translateX(-50%);
            font-size: 0.8rem; color: #d8cba7; background: #17151198;
            padding: 8px 16px; border-radius: 20px; backdrop-filter: blur(4px);
            pointer-events: none; border: 1px solid #3a331fcc;
        }
        #canvas-container { width: 100vw; height: 100vh; display: block; }
    </style>
    <!-- Import Three.js and PLYLoader via CDN -->
    <script async src="https://unpkg.com/es-module-shims@1.8.0/dist/es-module-shims.js"></script>
    <script type="importmap">
      {
        "imports": {
          "three": "https://unpkg.com/three@0.160.0/build/three.module.js",
          "three/addons/": "https://unpkg.com/three@0.160.0/examples/jsm/"
        }
      }
    </script>
</head>
<body>
    <div id="ui-layer">
        <h1>__TITLE__</h1>
        <div class="sub">__SUBTITLE__</div>
    </div>
    <div class="hint">Left Click: Rotate | Right Click: Pan | Scroll: Zoom</div>
    <div id="canvas-container"></div>

    <script type="module">
        import * as THREE from 'three';
        import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
        import { PLYLoader } from 'three/addons/loaders/PLYLoader.js';

        // 1. Setup Scene
        const container = document.getElementById('canvas-container');
        const scene = new THREE.Scene();
        
        // 2. Setup Camera
        const camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 100);
        camera.position.set(0, 0, 3);

        // 3. Setup Renderer
        const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
        renderer.setSize(window.innerWidth, window.innerHeight);
        renderer.setPixelRatio(window.devicePixelRatio);
        container.appendChild(renderer.domElement);

        // 4. Setup Controls
        const controls = new OrbitControls(camera, renderer.domElement);
        controls.enableDamping = true;
        controls.dampingFactor = 0.05;

        // 5. Lighting
        const ambientLight = new THREE.AmbientLight(0xffffff, 0.6);
        scene.add(ambientLight);
        const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);
        dirLight.position.set(5, 5, 5);
        scene.add(dirLight);

        // 6. Load PLY Model
        const loader = new PLYLoader();
        loader.load('__MODEL_PATH__', function (geometry) {
            geometry.computeVertexNormals(); // Required for lighting to work on meshes
            geometry.center(); // Center the model in the viewport

            // Determine if it's a mesh or a point cloud based on indices
            let object;
            if (geometry.index) {
                // It's a mesh
                const material = new THREE.MeshStandardMaterial({ 
                    vertexColors: true, // Use colors generated by SfM
                    side: THREE.DoubleSide,
                    roughness: 0.8
                });
                object = new THREE.Mesh(geometry, material);
            } else {
                // It's a sparse point cloud
                const material = new THREE.PointsMaterial({ 
                    vertexColors: true, 
                    size: 0.02 
                });
                object = new THREE.Points(geometry, material);
            }

            // Scale adjustment (SfM coordinates can be huge or tiny)
            object.scale.set(1.5, 1.5, 1.5);
            scene.add(object);
        });

        // 7. Animation Loop
        function animate() {
            requestAnimationFrame(animate);
            controls.update();
            renderer.render(scene, camera);
        }
        animate();

        // 8. Handle Window Resize
        window.addEventListener('resize', onWindowResize, false);
        function onWindowResize() {
            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();
            renderer.setSize(window.innerWidth, window.innerHeight);
        }
    </script>
</body>
</html>
"""

def main():
    if not os.path.exists(SFM_OUT_DIR):
        print(f"No SfM outputs found at {SFM_OUT_DIR}. Run sfm_pipeline.py first.")
        return

    # 1. Discover garment folders (e.g., 'Blue Dress')
    garments = [d for d in os.listdir(SFM_OUT_DIR) if os.path.isdir(os.path.join(SFM_OUT_DIR, d))]
    
    # Create a list of targets to process: tuples of (Display Name, Source Directory)
    targets = [(g, os.path.join(SFM_OUT_DIR, g)) for g in garments]

    # 2. Check for root-level PLY files directly in sfm_out/ (from previous generic runs)
    has_root_mesh = os.path.exists(os.path.join(SFM_OUT_DIR, "mesh.ply"))
    has_root_cloud = os.path.exists(os.path.join(SFM_OUT_DIR, "sparse_cloud.ply"))
    
    if has_root_mesh or has_root_cloud:
        targets.append(("Default Model", SFM_OUT_DIR))

    if not targets:
        print("No models found in outputs/sfm_out/ or its subfolders.")
        return

    for garment_name, garment_dir in targets:
        # Check for mesh first, fallback to sparse cloud
        mesh_src = os.path.join(garment_dir, "mesh.ply")
        cloud_src = os.path.join(garment_dir, "sparse_cloud.ply")
        
        target_src = None
        model_type = ""
        
        if os.path.exists(mesh_src):
            target_src = mesh_src
            model_type = "Poisson Mesh"
        elif os.path.exists(cloud_src):
            target_src = cloud_src
            model_type = "Sparse Point Cloud"
        else:
            print(f"Skipping {garment_name}: Neither mesh.ply nor sparse_cloud.ply found.")
            continue

        # Create safe filenames
        safe_name = garment_name.replace(" ", "_").lower()
        model_filename = f"{safe_name}.ply"
        html_filename = f"{safe_name}_3d.html"
        
        model_dest = os.path.join(MODELS_DIR, model_filename)
        html_dest = os.path.join(VIEWER_DIR, html_filename)

        # 1. Copy the 3D model to the viewer/models/ directory
        shutil.copy2(target_src, model_dest)

        # 2. Generate the HTML
        # The path in HTML is relative to the viewer folder (e.g., 'models/blue_dress.ply')
        relative_model_path = f"models/{model_filename}"
        subtitle = f"Real-time WebGL Rendering &mdash; {model_type}"

        html = HTML_TEMPLATE
        html = html.replace("__TITLE__", garment_name)
        html = html.replace("__SUBTITLE__", subtitle)
        html = html.replace("__MODEL_PATH__", relative_model_path)

        with open(html_dest, "w") as f:
            f.write(html)

        print(f"Built 3D Viewer for {garment_name}:")
        print(f"  -> Model: viewer/{relative_model_path}")
        print(f"  -> HTML:  viewer/{html_filename}\n")

if __name__ == "__main__":
    main()